// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHBfQS2p7ZrR-vPb_X9EoizQ1MmBrlVX4',
    appId: '1:904362762428:web:a0f8edcf03c6bd5c06f0b9',
    messagingSenderId: '904362762428',
    projectId: 'states-f422a',
    authDomain: 'states-f422a.firebaseapp.com',
    storageBucket: 'states-f422a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACyPCOZoM_3d-gEj7V8jOqOhUwmHpNZy8',
    appId: '1:904362762428:android:6e3d6aafb2ab707c06f0b9',
    messagingSenderId: '904362762428',
    projectId: 'states-f422a',
    storageBucket: 'states-f422a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMZiao7J7578-jDGYKR3miG-_nq85RG0I',
    appId: '1:904362762428:ios:37fe7f1898f15ca806f0b9',
    messagingSenderId: '904362762428',
    projectId: 'states-f422a',
    storageBucket: 'states-f422a.appspot.com',
    iosClientId: '904362762428-n7mp4bk4rtcdol7ee9h77ikdjarfjjpp.apps.googleusercontent.com',
    iosBundleId: 'com.example.states',
  );
}
